### ISSUE TITLE
Detect and flag unsorted dependency lists

### ISSUE THREAD

**Issue by jamesonwilliams** [autonomousapps/gradle-best-practices-plugin#2]
Let's say I have a `dependencies` block, like:

```groovy
dependencies {
    implementation project(':foo')
    implementation project(':bar')
}
```

`:foo` is out of lexicographic order with respect to `:bar` in this block. For modules with huge dependency lists, this situation becomes a maintenance burden:
1. It's hard to read the dependencies list, and
2. Updates to the list may conceal the changed dependencies during code review.

I'm not sure if this `gradle-best-practices-plugin` project would be an appropriate home for this check - but I thought I'd ask! 

See also: https://github.com/nebula-plugins/gradle-lint-plugin/issues/113

**Comment by autonomousapps** [comment]
I think this isn't a good use-case for this plugin. I do have an alternative project that is nearly ready to be published that will solve this, though.
